### ISSUE TITLE
Can't get post the "Accept" button

### ISSUE THREAD

**Issue by maysara** [roysix/url-incrementer#1]
I've just added the plugin to chromium on ubuntu 14.04, I'm unable to use it because it wont get beyond the popup and hitting accept gets me no where, nor activates ">"  or "<"

**Comment by sixcious** [comment]
Hi,

Interesting! Could you post which version of Chrome? I believe the extension uses some features that are only available in Chrome 43/44+. I'll download and try an Ubuntu live USB stick and investigate.

Sincere apologies for the inconvenience and thanks for posting this issue.

**Comment by maysara** [comment]
Seems to be the case, Its chromium Version 39.0.2171.65 Ubuntu 14.04 (64-bit) ; chrome web store said "This item is compatible with your device"

**Comment by sixcious** [comment]
Yes, it is the Chrome version. I tried it on Ubuntu with Chrome 45 and it seems to work fine.

I didn't know Linux doesn't auto-update your Chrome like Windows does, so thank you for bringing this up.

I'll update the "minimum_chrome_version" in the manifest so no one else encounters this.

My sincere apologies again.

**Comment by maysara** [comment]
Thanks for the careful followup
