### ISSUE TITLE
URL increment/decrement one-click buttons do not work correctly with bases >10

### ISSUE THREAD

**Issue by wbl2yj** [roysix/url-incrementer#10]
**Describe the bug**
I am attempting to scrape information about Unicode characters from unicode-table.com. These characters are in base-16 (hexadecimal). The issue is that the one-click button can increment in hex but only detect in decimal. For example, incrementing on the following page: https://unicode-table.com/en/0009/ will go to /000A/, but incrementing again goes to /001A/ instead of /000B/. (I have only tested with the one-click increment, not decrement, but I imagine a similar bug exists for it for e.g. /0020/ -> /001F/ -> /000F/).
It works if I use the multi-click method, but the single-click is faster and easier to automate.

**URL**
https://unicode-table.com/en/000A/

**Environment**
Windows 10 Pro
Chrome Version 89.0.4389.114 (Official Build) (64-bit)
URL Incrementer Version 5.8
URL Increment Button Version 5.9

**Comment by sixcious** [comment]
Hi @wbl2yj

Thanks for opening this issue and for using URLI!

I can't replicate this, so let me explain how URLI and the 1-Click Buttons are designed to work.

The 1-Click Buttons are flexible and designed to work with *or* without URL Incrementer. They were originally only intended to work with URLI, but I recently updated them last month to be able to work without URLI.

However, if URL Incrementer isn't installed/enabled, the buttons will always default to increment/decrement in Base 10 (Decimal). They will *not* try to "auto-detect" the base type that you're trying to increment. I will *never* ever try to "lock you in" to an auto-detected base type (which I may guess wrong) and "assume" what you're trying to do other than Base 10. And that approach wouldn't work in the upcoming Version 6.0, where we have to worry about completely variable base types like `Date Time`, `Roman Numeral`, `Decimal Number`, and even a user-defined `Custom Base Alphabet`.

If you want the 1-Click Buttons to increment in Hexadecimal, then you need to have URLI installed and you need to go in the Setup window, choose Hexadecimal and click the Accept button.

Once URLI is "enabled" with the settings you want, the buttons will simply send a message to URLI to increment in Hexadecimal (or whatever settings you set it up as). However, you need to have them _both_ installed/enabled.

If I misunderstood your issue, please feel free to clarify, but I'm closing this issue for the time being.

I hope this helps!

**Comment by wbl2yj** [comment]
I figured out the issue, and it is indeed easy for the user to manually configure. There is an additional step beyond simply selecting hexadecimal. You have to also increment at least once using URLI (rather than the one-click) and, in the URLI pop-up, set the exact location/length to increment in the URL. The issue was not that it was auto-detecting the base, but that it was auto-detecting the length.

Thus, initially, it was reading 0009 as 4 digits and incrementing the last digit, but reading 000A as only 3 digits and again incrementing the "last" digit. I think this is still unintended behavior but not one that causes any real inconvenience once you know how to manually configure it.

I was initially trying to detect where to edit using a regex: [\da-f]{4}. This detected the correct place in the URL but still didn't configure the length. It seems to remember it across all pages once I manually highlighted it.

Anyways, thanks for the advice. I figured it out and hopefully this discussion also helps someone else if they experience a similar issue.
