### ISSUE TITLE
Doesn't appear to work on Android mobile versions.

### ISSUE THREAD

**Issue by HowdHe** [roysix/url-incrementer#12]
If there is a way to make this work on a mobile browser, I can't figure it out. On kiwi, for instance, it will add the extension, but attempts to use it just open a new tab without any content aside from the incrementer buttons.

Tbh, what I'd love to see most is a version for the Samsung Internet App.

**Comment by sixcious** [comment]
Hi HowdHe. Thanks for opening this issue and for using URLI!

URLI can work on Android/Mobile with the Firefox Nightly browser. This is the only browser I personally use and *try* to offer support for on Android. I've added instructions in the [Help Guide](https://github.com/roysix/url-incrementer/wiki/Help#android-support) on how to get it working.

I've also added a note about the "new tab" thing you mentioned in case that might help you with getting it working on Kiwi, though I unfortunately can't really offer any specific support/guidance for that browser or Samsung Internet. (I already have my hands full making sure URLI works for Desktop Chrome, Edge, and Firefox as it is!)

Hope this helps!

**Comment by HowdHe** [comment]
Oh, awesome. Thanks for the advice. I definitely wouldn't have figured out how to set that up without that primer. It works on Firefox nightly. A little clunky. Using the increment button alternative is easier, but still a little clunky. I wish it was possible to customize the toolbar and drag the addons there for quick access.

Here's something I noticed: on Firefox nightly, it isn't possible to manually reorder addons. They are listed in alphabetical order. It feels a little counterintuitive that Decrement is above Increment, but worse yet, they get separated if another addon's name falls between them. If you wanted to counteract this quirk, they could be renamed with a special character as the leading character, like "[ + ] Increment" and "[ - ] Decrement".

**Comment by sixcious** [comment]
Yes, it's certainly a bit clunky to use on Android.

Two things you may wish to try to make it work better:

1. Inside URLI's Options Page (Firefox Nightly: `Menu > Addons > Addon Manager > URL Incrementer > Settings`), you can try enabling the `Mouse` shortcuts for Increment and/or Decrement. You can use `Left` Clicks for touch/tap and set the number of Clicks (Taps) to something high like 5 or 4. Or  you can set it to a lower value like 2 or 3 Clicks (Taps) and then clear the Mouse shortcut when you're done incrementing so it doesn't interfere in the future.

2. [Infy Scroll](https://github.com/roysix/infy-scroll) can increment URLs and append each page as you scroll down. It may not work on all sites, but it would be a lot more convenient than using URLI on Android.

Thanks for trying it out and for the reordering tip!
