### ISSUE TITLE
how do you use custom base?

### ISSUE THREAD

**Issue by ovladuk** [roysix/url-incrementer#13]
how do you use custom base? i don't see the option anywhere.

**Comment by sixcious** [comment]
Hi, thanks for opening this issue.

Custom Bases are currently only in the [Firefox version](https://addons.mozilla.org/firefox/addon/url-incrementer/), which is a beta of the upcoming Version 6.0.

**Comment by ovladuk** [comment]
> 

ohh ok ill have to start the engine on firefox! does that mean the next chrome version will have a custom database?

**Comment by sixcious** [comment]
Yes, it will be able to increment Custom Bases, Dates and Times, Roman Numerals, and more. It should be out sometime this year.

Thanks.

**Comment by sixcious** [comment]
Hi, sorry for the super long delay, but Custom Bases are now available in Version 6 for Chrome, Firefox, and Edge.

Thank you for opening this issue! ❤️
