### ISSUE TITLE
License for the core algo

### ISSUE THREAD

**Issue by aehlke** [roysix/url-incrementer#15]
Hi, I'd like to suggest you use MPL/Apache/MIT for the core "next page" detection file. I understand your hesitancy to other browser extension devs copying your work, however I'm interested in this logic for an unrelated project (within an iOS/Mac app I'm making independently focused on language learning, not for a Chrome/Safari extension). Even a one-time license for me specifically would be convenient if you're not ready for public relicensing. Let me know if I should contact you another way instead. Thanks very much.

**Comment by sixcious** [comment]
Hi aehlke!

Yes, you can use [next-prev.js](https://github.com/sixcious/url-incrementer/blob/main/src/js/next-prev.js) in your app. Thank you for asking.

I'm still not ready to decide on a license for the entire project; if it were a library or component that was meant to be reused in another project, I'd MIT it, but it's more of an end-product/app, so for now, I'll keep it as TBD until I can  find a license that I can agree with (or find some time to modularize the next code into its own separate library).

Best of luck with your app. 💜

**Comment by aehlke** [comment]
Thank you very much!

I recommend you split it into an MIT lib and something else to your taste for the full app. You may find people interested in contributing as a lib for scraper use cases
