### ISSUE TITLE
message referes to "max" 

### ISSUE THREAD

**Issue by CarlFK** [roysix/url-incrementer#8]
If I set increment to -1, click accept, I get: 
"Interval has to be between 1 and Max"

"max" means nothing to me.

**Comment by sixcious** [comment]
Hi again CarlFK,

Sorry for the vague error message! "Max" here was meant to just mean JavaScript's [Number.MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER) value, `9007199254740991`.

I'll update the error message to be more descriptive and replace "Max" with the numerical value or something more descriptive so there is no ambiguity.  Thanks for opening this issue and helping improve URLI!
