### ISSUE TITLE
no code

### ISSUE THREAD

**Issue by CarlFK** [roysix/url-incrementer#9]
I can't find the source code in this repo.

**Comment by sixcious** [comment]
Hi again Carl,

I'm sorry for the delay. I've decided (for the time being at least) to keep URLI's source code on my computer. I'm in the process of developing a new major version with a new license and doing some cleanup work on the repository. You're always welcome to `Inspect` using your Browser's DevTools or use a CRX Viewer to view the source code and to make sure that nothing malicious is going on.

Thanks for using URLI and for opening this issue.
